# conda env create -f conda.env.pyG143.yml
name: pyG143
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - requests
  - setuptools
  # linter and formatter
  - pylint
  - black
  - isort
  # utility
  - tqdm
  # data analysis
  - h5py
  - numpy
  - scipy
  - pandas
  - scikit-learn
  # visualization
  - matplotlib
  - seaborn
  - plotly
  - nglview
  # cheminfo
  - openbabel
  - rdkit
  - biopython
  - chembl_webresource_client
  # molecular mechanics
  - openmm
  - ambertools
  - parmed
  - mdtraj
  - mdanalysis
  - openff-toolkit
  # machine learning
  - pytorch=1.8.1
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pip
  - pip:
    - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu102.html
    - torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu102.html
    - torch-geometric==1.4.3