# conda env create -f conda.env.fast.yml
name: fast
channels:
  - pytorch
  - rusty1s
  - conda-forge
dependencies:
  - python
  - jupyter
  - requests
  - setuptools
  # linter and formatter
  - pylint
  - black
  - isort
  # utility
  - tqdm
  # data analysis
  - h5py
  - numpy
  - scipy
  - pandas
  - scikit-learn
  # visualization
  - matplotlib
  - seaborn
  - plotly
  - nglview
  # cheminfo
  - openbabel
  - rdkit
  - biopython
  - chembl_webresource_client
  # molecular mechanics
  - openmm
  - ambertools
  - parmed
  - mdtraj
  - mdanalysis
  - openff-toolkit
  # machine learning
  - pytorch=1.8.1
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  # - pytorch-geometric